[build]
  base = "."
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/workflow/*"
  to = "/.netlify/functions/workflow/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/app/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
